services:
  - type: web
    name: youtube-downloader
    runtime: docker # سنستخدم Docker لأنه الحل الأضمن كما اتفقنا
    plan: free # أو الخطة التي تختارها
    envVars:
      - key: PORT
        value: 3000